---
- job:
    name: ansible-role-zookeeper
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run: tests/playbooks/post.yaml
    roles:
      - zuul: openstack/ansible-role-zookeeper

- job:
    name: ansible-role-zookeeper-fedora-latest
    parent: ansible-role-zookeeper
    nodeset: fedora-latest

- job:
    name: ansible-role-zookeeper-ubuntu-bionic
    parent: ansible-role-zookeeper
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-zookeeper-ubuntu-xenial
    parent: ansible-role-zookeeper
    nodeset: ubuntu-xenial

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-zookeeper-fedora-latest
        - ansible-role-zookeeper-ubuntu-bionic
        - ansible-role-zookeeper-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-zookeeper-fedora-latest
        - ansible-role-zookeeper-ubuntu-bionic
        - ansible-role-zookeeper-ubuntu-xenial
        - tox-linters
