---
- name: Init database
  command: "service {{ zookeeper_service_zookeeper_name }} init"

- name: Restart zookeeper
  service:
    name: "{{ zookeeper_service_zookeeper_name }}"
    enabled: "{{ zookeeper_service_zookeeper_enabled }}"
    state: "{{ zookeeper_service_zookeeper_state }}"
  when: zookeeper_service_zookeeper_manage
